image: Visual Studio 2017
artifacts:
  - path: '**\jsreport.Binary.OSX*.nupkg'
    name: nuget
    type: NuGetPackage
environment:
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
build:
  project: jsreport.Binary.OSX.sln
before_build:
  - cmd: dotnet restore
  - cmd: cd jsreport.Binary.OSX&&Powershell.exe -ExecutionPolicy ByPass -File download.ps1&&cd ..
deploy:
  provider: NuGet
  api_key:
    secure: UxdKl7p+OXiedpDaYECXtpfyKWhYDTseqXQlR4TEmqPpU2XoEPFZxiYPeX6cfdQ/
  on:
    appveyor_repo_tag: true
test_script:
- cd jsreport.Binary.OSX.Test
- dotnet test

